# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/mapper/crypted";
#      fsType = "btrfs";
#      options = [ "subvol=root" ];
#    };

#  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/b49a5add-85ff-43b2-8ce1-c3562ac5ce78";

#  fileSystems."/.swapvol" =
#    { device = "/dev/mapper/crypted";
#      fsType = "btrfs";
#      options = [ "subvol=swap" ];
#    };

#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/286E-D2DA";
#      fsType = "vfat";
#      options = [ "fmask=0077" "dmask=0077" ];
#    };

#  fileSystems."/home" =
#    { device = "/dev/mapper/crypted";
#      fsType = "btrfs";
#      options = [ "subvol=home" ];
#    };

#  fileSystems."/nix" =
#    { device = "/dev/mapper/crypted";
#      fsType = "btrfs";
#      options = [ "subvol=nix" ];
#    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
